<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>wiki</string>
		<string>sublime-wiki</string>
		<string>swiki</string>
	</array>
	<key>name</key>
	<string>Wiki</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Match WikiWords and make them into links.</string>
			<key>match</key>
			<string>([A-Z][a-z]+){2,}</string>
			<key>name</key>
			<string>markup.bold.link.internal.Wiki</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Simplest possible web address matcher. If you think this is basic, you should see the one in the Markdown syntax file.</string>
			<key>match</key>
			<string>((?:https?|ftp)://\S+)</string>
			<key>name</key>
			<string>string.quoted.link.external.Wiki</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>To find email</string>
			<key>match</key>
			<string>(\S+)@(\S*)\.(\S+)</string>
			<key>name</key>
			<string>string.quoted.link.email.Wiki</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>I know I don't need this, but I like strings to be called out.</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.Wiki</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Markdown-style bold</string>
			<key>match</key>
			<string>(\*\*|__)(.*?)(\*\*|__)</string>
			<key>name</key>
			<string>markup.bold.Wiki</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Markdown-style italics</string>
			<key>match</key>
			<string>[^\*_](\*|_)[^\*_]+?(\*|_)[^\*_]</string>
			<key>name</key>
			<string>markup.italic.Wiki</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.Wiki</string>
	<key>uuid</key>
	<string>14883dd8-b120-4a1e-a4c5-67c5e7815344</string>
</dict>
</plist>
